# AQUI É ONDE VOCÊ PODERÁ CONFIGURAR AS PROPRIEDADES DO PLUGIN...

# TEMPO EM MINUTOS QUE A BOLSA IRÁ SE ALTERAR...
stock-exchange-refresh: 10

# MENSSAGEM QUE SERÁ ENVIADA A TODOS OS JOGADORES QUANDO A BOLSA MUDAR DE VALOR...
stock-change-value-message: "§r\n§l§aBOLSA DE VALORES§r: §7A bolsa de valores agora está em §f{VALOR}%%§7!§r\n§r"